### PR TITLE
valid_move? for king queen bishop rook and knight

### PR DESCRIPTION
**Pull request by cbohara**
I updated valid_move? for king to include path_blocked?
I created valid_move? for rook, bishop, and queen to check movement and path_blocked?
I created valid_move? for knight to check movement (does not require path_blocked?)

I don't believe we have a means to keep track of the turns yet, but I will make the valid_move? for the pawn pieces once that is available because the pawns move 2 squares on their first turn only, otherwise they move one square.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Are you familiar with method overriding in subclasses?  We can utilize that to implement some shared checks inside `valid_move?` that apply to all the pieces.

An example of method overriding, using the massively-overused animal example:  :)

```ruby
class Animal
  def speak
    'animal sound'
  end
end

class UnknownAnimal < Animal
end

class Dog < Animal
  def speak
    'woof'
  end
end

class Cat < Animal
  def speak
    'meow'
  end
end

cat = Cat.new
dog = Dog.new
unknown = UnknownAnimal.new

cat.speak #=> 'meow'
dog.speak #=> 'woof'
unknown.speak #=> 'animal sound'
```

However when you are overriding a method, you can call a special method `super` which is the method on your parent class that you are overriding:

```ruby
class Animal
  def move
    # update the animal's position
    @position += 1
  end
end

class Dog < Animal
  def move
    super
    'walks'
  end
end

class Snake < Animal
  def move
    super
    'slithers'
  end
end

dog = Dog.new
snake = Snake.new

dog.move #=> 'walks'
snake.move #=> 'slithers'
```

So the dog and snake did different things, but both called `super` so the code in their parent class's `move` method executed as well, updating their position.  Silly example but it kinda illustrates the point.

For our `valid_move?` any shared checks that apply to all pieces can be factored out into the parent class, so for instance validating that the requested move is within the bounds of the board:

```ruby
class Piece < ActiveRecord::Base
  def valid_move?(x, y)
    # Check that the piece is in bounds
    return false if x < 0 || x > 7 || y < 0 || y > 7

    # All checks passed
    true
  end
end

class King < Piece
  # ensures king piece can only move 1 square in any direction
  def valid_move?(x,y)
    return false unless super(x, y)

    x_diff = x_diff(x)
    y_diff = y_diff(y)
    return (x_diff <= 1) && (y_diff <= 1)
  end
end
```

So, now each `valid_move?` in the sub-classes will call `super(x, y)`, which calls `valid_move?` on their parent class, and they return false if `super` does.

Make sense?  That way you don't have to duplicate common checks like that across all the pieces.  One extra benefit of OOP / STI.

**Comment by cbohara** [comment]
Hi Jacob! Thank you for taking the time to share all that info with me.  It does make sense for the most part, but I am confused by the line 'return false unless super(x, y)' in the king model.  I would assume it would be 'return false if super(x,y)'.  Could you explain that logic to me?  Thanks!

**Comment by jacobwgillespie** [comment]
Sure!  It's a simplification of the following:

```ruby
result_from_super = super(x, y)
if result_from_super == false
  # super (which is valid_move?) returned false, so the move is not valid and we should return false
  return false
else
  # continue with our method checks because super found nothing wrong
end
```

So, you can begin to compact that as follows:

```ruby
if super(x, y) == false
  return false
end
```

```ruby
return false if super(x, y) == false
```

```ruby
return false if !super(x, y)
```

```ruby
return false unless super(x, y)
```

You can also translate it into an english sentence like so:

```ruby
return false unless super(x, y)
# return false unless super(x, y) (returns true)
```

**Comment by cbohara** [comment]
awesome thank you!  that makes sense now.  i'll refactor my PR to incorporate all that jazz.

**Comment by cbohara** [comment]
@jacobwgillespie : one more question.  I shouldn't add path_blocked? to the piece model, correct?  Because path_blocked? only applies to the queen, rook, bishop, and pawn.

**Comment by jacobwgillespie** [comment]
It should be in the Piece model because it applies to multiple pieces.  It doesn't necessarily have to be called by every sub-class.  I'd leave it in the Piece class.

**Comment by cbohara** [comment]
Ah I poorly communicated that question.  Yes, path_blocked? should stay in the piece model as is.  I was double checking having this logic in the piece model...

correct:
`  def valid_move?(x,y)
    return false if x < 0 || x > 7 || y < 0 || y > 7
    return true
  end`

incorrect because path_blocked? does not apply to all pieces:
`  def valid_move?(x,y)
    return false if x < 0 || x > 7 || y < 0 || y > 7
    return false if path_blocked?(x,y)
    return true
  end`

**Comment by jacobwgillespie** [comment]
Ah, correct, you would only call `path_blocked?` inside the children classes as required.  👍

**Comment by cbohara** [comment]
I added valid_move? logic that applies to all pieces
I added a lot more comments to help the team follow along

**Pull request merged**
